import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/ui/header";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import UserProvider from "@/components/UserProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import { getUserByEmail } from "../../_lib/actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  const userProfile = await getUserByEmail(session?.user?.email);

  return (
    <html lang="en">
      <SessionProviderWrapper>
        <UserProvider value ={{session, userProfile}}>
        <body
          className={``}
        >
          <Header />
          {children}
        </body>
        </UserProvider>
      </SessionProviderWrapper>
    </html>
  );
}
