import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/ui/header";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import UserProvider from "@/components/UserProvider";
import { PopUpProvider } from "@/components/providers/PopUpProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import { getUserByEmail } from "../../_lib/actions";
import { redirect } from "next/navigation";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const sessionPromise = getServerSession(authOptions);
  const headersList = headers(); // Avoid multiple `headers()` calls
  const session = await sessionPromise;
  const userProfilePromise = session?.user?.email ? getUserByEmail(session?.user?.email) : null;
  const userProfile = await userProfilePromise; // Fetch in parallel

  return (
    <html lang="en">
      <body
        className={``}
      >
        <SessionProviderWrapper>
          <UserProvider value={{ session, userProfile }}>
            <PopUpProvider>
              <Header />
              {children}
            </PopUpProvider>
          </UserProvider>
        </SessionProviderWrapper>
      </body>
    </html >
  );
}
