import Link from "next/link";
import { Button } from "@/components/ui/button";
import Pricing from "@/components/landingPage/Pricing";
import GenerateOneMeal from "@/components/landingPage/GenerateOneMeal";
import KeyAdvantages from "@/components/KeyAdvantages";
import HowItWorks from "@/components/HowItWork";
import CTASection from "@/components/CtaSection";
import HeroAIMenu from "@/components/HeroAiMenu";

export default function Home() {

  return (
    <div className="w-full">
      <HeroAIMenu />
      <div id='keyAdvantages'>
        <KeyAdvantages />
        <div>
          {/* some image */}

          <div>
            <h3 className="font-bold">No Pre-Defined Meals</h3>
            <p>Each menu is uniquely generated by AI, tailored to your preferences—no generic plans, just food that fits you.</p>
          </div>
        </div>
        <div>
          {/* some image */}
          <div>
            <h3 className="font-bold">Stay on Track While Traveling</h3>
            <p>Your routine shouldn’t suffer just because you're on a trip. Simply update your location, and FoodSm.art will find meals that match your taste wherever you are.</p>
          </div>
        </div>
        <div>
          {/* some image */}
          <div>
            <h3 className="font-bold">Anything is possible</h3>
            <p>Want to eat like your favorite celebrity? Have dietary restrictions? Just type what you need — our AI understands and delivers.
              {/* <br /> Want meals inspired by your favorite restaurant? Just type the name, and our AI will suggest something similar. */}
            </p>
          </div>
        </div>
      </div>
      <div id='generateOneMeal' className="px-4 py-20 flex flex-col justify-center items-center w-full">
        <h2>Try generating a meal yourself:</h2>
        <GenerateOneMeal className='flex flex-1 w-full' />
      </div>
      <div id='howItWorks'>
        <HowItWorks />
        <h2>How it works</h2>
        <div>
          {/* some image */}
          <div>
            <h3 className="font-bold">Complete onboarding</h3>
            <p> quick, friendly chat — just 4-5 easy questions — to figure out what works best for you.</p>
          </div>
        </div>
        <div>
          {/* some image */}
          <div>
            <h3 className="font-bold">Start using FoodSm.art</h3>
            <p>Every liked or disliked meal fine-tunes your preferences, helping FoodSm.art suggest better meals just for you.</p>
          </div>
        </div>
        <div>
          {/* some image */}
          <div>
            <h3 className="font-bold">Plans changed? Just update your profile</h3>
            <p>Traveling or adjusting your goals? No waiting — edit your profile, and your next meal adapts instantly.</p>
          </div>
        </div>
      </div>

      {/* <div id='testimonials'>
      
      </div> */}
      <div id='plans'>
        <Pricing />
      </div>
      <div id='cta' className="flex flex-col items-center justify-center">
        <CTASection />
        <span>Still thinking?</span>
        <span>Watch our demo video</span>
        {/* Some video */}
        <Button>Start free trial</Button>
      </div>
    </div>
  );
}


