import { Sparkles, Compass, MessageSquareText, MapPinPlusIcon } from "lucide-react";

const features = [
  {
    icon: <Sparkles className="h-6 w-6 text-primary" />, 
    title: "No Pre-Defined Meals",
    description: "Each menu is uniquely generated by AI, tailored to your preferences—no generic plans, just food that fits you."
  },
  {
    icon: <MapPinPlusIcon className="h-6 w-6 text-primary" />, 
    title: "Stay on Track While Traveling",
    description: "Your routine shouldn't suffer just because you're on a trip. Simply update your location, and FoodSm.art will find meals that match your taste wherever you are."
  },
  {
    icon: <MessageSquareText className="h-6 w-6 text-primary" />, 
    title: "Anything is Possible",
    description: "Want to eat like your favorite celebrity? Have dietary restrictions? Just type what you need — our AI understands and delivers."
  }
];

export default function KeyAdvantages() {
  return (
    <section className="py-20 bg-slate-50 dark:bg-slate-900">
      <div className="container mx-auto px-4 text-center">
        <h2 className="text-3xl font-bold text-slate-900 dark:text-white mb-4">Why Choose FoodSm.art?</h2>
        <p className="text-lg text-slate-600 dark:text-slate-300 max-w-2xl mx-auto mb-12">
          Our AI-powered platform offers unique advantages that make meal planning effortless and personalized.
        </p>

        <div className="grid md:grid-cols-3 gap-8">
          {features.map(({ icon, title, description }, index) => (
            <div
              key={index}
              className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-sm border border-slate-200 dark:border-slate-700 transition-all hover:shadow-md"
            >
              <div className="h-12 w-12 bg-primary/10 rounded-lg flex items-center justify-center mb-6">
                {icon}
              </div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">{title}</h3>
              <p className="text-slate-600 dark:text-slate-300 text-pretty">{description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
